Loaded module: python3/3.8.2
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "1d_landmarks.py", line 163, in <module>
    main()
  File "1d_landmarks.py", line 143, in main
    _, Xt = sde.approx_p0(q0, p0, vT, SigmaT, LT, 
  File "/zhome/77/8/118225/Desktop/Landmarks/Github/SDE_finite_landmarks/sde_approx.py", line 463, in approx_p0
    Wt, Xt = self.__approx_p0(x0, p0)
  File "/zhome/77/8/118225/Desktop/Landmarks/Github/SDE_finite_landmarks/sde_approx.py", line 515, in __approx_p0
    p0, Xt = self.__al_52(p0, None, Wt)
  File "/zhome/77/8/118225/Desktop/Landmarks/Github/SDE_finite_landmarks/sde_approx.py", line 670, in __al_52
    return p0, Xt
UnboundLocalError: local variable 'Xt' referenced before assignment
